* directions

>north
You have heard of compass directions like north, but they don't make any sense here.
Instead, you can go spinward, antispinward, port, and starboard.
When you look spinward, port is left and starboard is right.

[You can use the abbreviations SW, ASW, P, and S. You can also go UP, DOWN, IN, or OUT where appropriate. Type EXITS if you get confused about geography.]

>south
You have heard of compass directions like

>n
You have heard of compass directions like

>s
The exits are 

>port
The exits are 
