* scanner

>scanner, help
Recognized commands are HELP and SCAN.
You can ask the scanner for a list of commands by typing SCANNER, HELP and give it voice commands by typing phrases such as SCANNER, SCAN SOMETHING where SOMETHING is a visible object.

>scanner, scan me
License error: upgrade to a 3000-series model to scan organic lifeforms.

>scanner, scan jumpsuit
No modular technology detected.

>scanner, scan blanket
Technology detected. Suggest more specific scan.

>scanner, scan scanner
Machine is functional.

>scanner, go north
Syntax error: command not in vocabulary.

>scanner, perambulate
Syntax error: command not in vocabulary.

>scanner, scan cheddar
Search error: cannot find cheddar.

>scanner, scan the cheddar
Search error: cannot find the cheddar.
