*sleep

>sleep
But you just woke up.

>d
>get mask
>u
>get blanket
>out
>sw
>in
>get eraser
>erase board
>get power from machine
>out
>sw
>d
>search crate
>get boots
>hit eraser
>u
>wear boots
>wear mask
>asw
>asw
>asw
>up
>turn breaker on
>d
>asw
>remove boots
>enter pond
>remove mask
>wear boots
>wear blanket
>asw
>in
>get hoe
>out
>d
>get all from pump
>scan regulator
>scan unscanned regulator
>put functional regulator in pump
>scan power module
>scan unscanned power module
>put functional power module in pump
>close ceiling hatch
>port
>get communications unit
>starboard

>sleep
Not while you're standing up.

>drop blanket
You arrange the blanket on the ground.

>lie on blanket
You get onto the blanket.

>sleep
You are exhausted, mentally and physically, and sleep comes easily.
Tomorrow, you will start early and catch up on your missed chores.
Maybe this is how you are meant to live. Maybe things are better this way.
You stayed behind
Would you like to RESTART, RESTORE a saved game, QUIT, or WAKE up and continue your story?

> wake
You sleep, but restlessly and only for a few hours.
Then, you wake up, sweaty and chasing faint memories of unsettling dreams about your parents.
Pod Control 

>sleep
But you just woke up.
